FROM python:3.11

# Set the working directory
WORKDIR /app

COPY . .

# Install uv
RUN pip install uv

# Create virtual environment using uv
RUN uv venv --python 3.11 && \
    . .venv/bin/activate && \
    uv pip install -r requirements.txt && \
    uv pip install browser-use

# Install Playwright and its dependencies
RUN . .venv/bin/activate && \
    playwright install --with-deps

RUN . .venv/bin/activate && \
uv pip install fastapi uvicorn[standard]

EXPOSE 8000

CMD [".venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
